### ISSUE TITLE
Issue when trying to login

### ISSUE THREAD

**Issue by talmax1124** [adrianhajdin/project_shareme_social_media#1]
<img width="427" alt="Screen Shot 2021-12-22 at 4 34 20 AM" src="https://user-images.githubusercontent.com/61528430/147071232-d13c4b0a-5582-4506-9fad-a97d15b68a90.png">

When uploading to netlify, and fixing all the errors stated in the video, this message comes out

**Comment by handxr** [comment]
How did you fix  it? Same issue here
